# install.packages("lmtest")
library(lmtest)
head(cars)
attach(cars)
View(cars)
plot(dist,speed,main="scatter plot")
scatter.smooth(dist,speed,main="scatter plot")
cor(dist,speed)
model=lm(dist~speed)
model
summary(model)
fit=fitted.values(model)
fit
res=resid(model)
sum(res)
sum(fit)
sum(dist)
confint(model, level = 0.99)
dwtest(dist~speed)